### ISSUE TITLE
No loading using the core

### ISSUE THREAD

**Issue by Jackburton69** [wickerwaka/Arcade-IremM92_MiSTer#23]
Hello,
I using your core on a Mister2jamma.
When i load any game from your core i don't have the loading splash screen like any other core on the MiSTer.
I saw the check of the ram but nothing else (i can see the core option when i push the correct button)
If i try and retry sometime i can go the the splash screen of the game (Ninjabaseball for ex) but nothing else.

This is normal to don't have the loading splash screen with the loading of the rom ?

I attached what I have on the ram check screen

Best
!
[IMG_20230329_232811](https://user-images.githubusercontent.com/74626824/229290338-5f6c72fb-fb04-43cd-9800-7ea55b5ed1ff.jpg)

**Comment by Toryalai1** [comment]
The core is still in alpha state so please wait until it is in beta/released state. The core is being updated and stuff that wouldn't today might work tomorrow

This can be closed

**Comment by wickerwaka** [comment]
40c060f5f184e92dc46cf664fbd1cc6174007552 has restored support for keyboard encoders.
