### ISSUE TITLE
High scores not saving 

### ISSUE THREAD

**Issue by theenemy-thd** [wickerwaka/Arcade-IremM92_MiSTer#27]
I see there was an autosave option which I turned on but the high score table wasn't saving The game I was testing was rtype Leo.

Am I doing something wrong or not put something somewhere i should. I have only placed the rbf in cores and mra file in arcade.

Apologies if I'm being a total newbie

**Comment by Toryalai1** [comment]
High score hasn't been added yet. You can close this issue

**Comment by theenemy-thd** [comment]
Ahh ok ... 👍
