### ISSUE TITLE
Superior Soldiers - Crash

### ISSUE THREAD

**Issue by lsnderick** [wickerwaka/Arcade-IremM92_MiSTer#29]
After quick testing the new IremM92_20230413.rbf I've noticed that this game always crashes during attract demo when "Demo Sounds" DIP is enabled. If you start with it turned on the game hangs soon after the first demo fight begins, if the game was started without demo sound it crashes immediately after enabling it.

**Comment by wickerwaka** [comment]
Moved to https://github.com/MiSTer-devel/Arcade-IremM92_MiSTer/issues/4
