### ISSUE TITLE
button mapping naming convention

### ISSUE THREAD

**Issue by konradpop** [wickerwaka/Arcade-IremM92_MiSTer#3]
all games refer to the in the hunt button naming labels. Should be specific for each core.

**Comment by Toryalai1** [comment]
This is now solved: https://github.com/wickerwaka/Arcade-IremM92_MiSTer/commit/d0b53fa7cf9b42c7385ee8c4a7476eb1ae37a922

**Comment by wickerwaka** [comment]
Yes, thank you got the names list @Toryalai1
