### ISSUE TITLE
55hz mode outputs 60hz instead

### ISSUE THREAD

**Issue by Sheeg** [wickerwaka/Arcade-IremM92_MiSTer#6]
Even if I set my a 55hz video mode in my MiSTer ini file, the core will load at 55hz initially, then immediately switch to 60hz after the rom is loaded, toggling the video modes in the menu does nothing.

Hopefully this is known, but just posting here so it's tracked.

**Comment by wickerwaka** [comment]
This is an old option left over from the M72 code. M92 hardware runs at a pretty standard 60hz, so no need for video timing toggles. The option has been removed in 16bdfba8b5ffe095bf7763aee970a269969134ae
