### ISSUE TITLE
P2 Start

### ISSUE THREAD

**Issue by misteraddons** [wickerwaka/Arcade-IremM92_MiSTer#7]
P2 Start maps to player 1 controls for debugging purposes. Perhaps adding logic to allow P2 Start from P1. Perhaps add an OR statement to accept "P2 Start" button from joystick 1, or "Start" from joystick 2.
`wire m_start2   = btn_2p_start | joy[10] | joystick_1[8];`

**Comment by wickerwaka** [comment]
Fixed 16bdfba8b5ffe095bf7763aee970a269969134ae
